version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cicd
    
permissions:
  - object: /home/ubuntu/cicd
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
     -directory
     
hooks:
  AfterInstall:
    - location: script/install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu
