version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: script/after_install.sh
      timeout: 300
      runas: ubuntu
