version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/nodeapp

permissions:
  - object: /home/ec2-user/nodeapp
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: script/after_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: ec2-user
