version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cicd

permissions:
  - object: /home/ubuntu/cicd
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: script/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: ubuntu
