version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: script/install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: ubuntu
